# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: SSISBuild@1
  inputs:
    projectPath: '.'
    stripSensitive: false
    outputPath: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    targetPath: 
    artifactName: 'SSISArtifact'
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: SSISDeploy@1
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)'
    destinationType: 'ssisdb'
    destinationServer: 'mx01222.database.windows.net'
    destinationPath: '/SSISDB/AzurePackage'
    authType: 'sql'
    username: 'farhan'
    password: 'Manager12'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
